version: '3.8'

services:
  file-compressor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-compressor-app
    restart: unless-stopped
    ports:
      - "5500:5000"  # Port libre d'après votre liste
    volumes:
      - file_compressor_uploads:/app/uploads
      - file_compressor_compressed:/app/compressed
      - /etc/localtime:/etc/localtime:ro  # Synchronisation timezone
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Paris  # Ajustez selon votre timezone
      - MAX_CONTENT_LENGTH=1073741824  # 1GB en bytes
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/api/supported-formats')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"  # Si vous utilisez Traefik
      - "traefik.http.routers.file-compressor.rule=Host(`compressor.yourdomain.com`)"
      - "traefik.http.services.file-compressor.loadbalancer.server.port=5000"
      # Métadonnées pour identification
      - "com.docker.compose.project=file-compressor"
      - "com.docker.compose.service=app"
      - "description=Compresseur de fichiers multimédia"
      - "version=1.0.0"
    networks:
      - file-compressor-network

networks:
  file-compressor-network:
    driver: bridge
    name: file-compressor-net

volumes:
  file_compressor_uploads:
    name: file_compressor_uploads
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/docker-data/file-compressor/uploads  # Chemin sur votre serveur
  file_compressor_compressed:
    name: file_compressor_compressed
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/docker-data/file-compressor/compressed